
CREATE VIEW [dbo].[Property]
AS
SELECT [PropertyKey] AS [Property Key]
	,[SourceProductId] AS [Source Product Id]
	,[OPANumber] AS [OPA Number]
	,[OPANumberT] AS [OPA Number Technical]
	,[PropertyName] AS [Property Name]
	,[ShortName] AS [Short Name (Property)]
	,[GenericName] AS [Generic Name]
	,[AreaOfBusiness] AS [Area Of Business]
	,[AreaOfBusinessT] AS [Area Of Business Technical]
	,[AreaOfBusinessSuffix] AS [Area Of Business Suffix]
	,[AreaOfBusinessSuffixT] AS [Area Of Business Suffix Technical]
	,[PropertyCategoryType] AS [Property Category Type]
	,[PropertyCategory] AS [Property Category]
	,[BillingCompany] AS [Billing Company]
	,[IssueSite] AS [Issue Site]
	,[AccountantResponsible] AS [Accountant Responsible]
	,[ExecResponsible] AS [Exec Responsible]
	,[ProjectionYear] AS [Projection Year]
	,[IncomeProjectionDate] AS [Income Projection Date]
	,[IncomeProjectionDateINT] AS [Income Projection Date INT]
	,[SalesCategoryMDS] AS [Sales Category (MDS)]
	,[AbbreviationMDS] AS [Abbreviation]
	,[CommissionMDS] AS [Commission]
	,[CommissionNumMDS] AS [Commission INT]
	,[CommentMDS] AS [Commission Comment] 
	,[LegalContact] AS [Legal Contact]
	,[InvoiceCategory] AS [Invoice Category]
	,[HeadOfSport] AS [Head Of Sport]
	,[HeadOfBusinessUnit] AS [Head Of Business Unit]
	,[IsReplayReport] AS [Is Replay Report]
	,[IsOmitException] AS [Is Omit Exception]
	,[ClientCountry] AS [Client Country]
	,[ClientName]	AS [Client Name]
	,[ClientNo] AS [Client No]
	,[ClientAddress] AS [Client Address]
	,[IsIMGClient] AS [Is IMG Client]
	,Licensor AS [Licensor]
	,ContractingParty AS [Contracting Party]
	,BroadcastDateFrom AS [Broadcast Date From]
	,BroadcastDateTo AS [Broadcast Date To]
	,[ParentPropertyKey] AS [Parent Property Key]
	,[ReportingType] AS [Reporting Type]
	,[PremiereDate] AS [Premiere Date]
	,[AvailabilityDate] AS [Availability Date]
	,[CreatedDate] AS [Created Date]
	,[CreatedBy] AS [Created By]
	,[UpdatedDate] AS [Updated Date]
	,[UpdatedBy] AS [Updated By]
	,[Comment] AS [Comment]
	,[CommentCreatedBy] AS [Comment Created By]
	,[CommentCreatedDate] AS [Comment Created Date]
	,[ImgAsAuthorisedSignatory] AS [Img As Authorised Signatory]
	,[LicensorInDeal] AS [Licensor In Deal]
	,[IncludeInOutputDeal] AS [Include In Output Deal]
	,[SellAtRisk] AS [Sell At Risk]
	,[LegalOnlineNo] AS [Legal Online No]
	,[ContractStatus] AS [Contract Status]
  FROM [dbo].[DimProperty];
GO


GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[Property] TO [DataServices]
    AS [dbo];
GO

