CREATE TABLE [dbo].[DimProperty] (
    [PropertyKey]             BIGINT           NOT NULL,
    [SourceProductId]         INT              NOT NULL,
    [OPANumber]               VARCHAR (12)     NOT NULL,
    [OPANumberT]              VARCHAR (12)     NOT NULL,
    [PropertyName]            VARCHAR (50)     NOT NULL,
    [ShortName]               VARCHAR (30)     NOT NULL,
    [GenericName]             VARCHAR (30)     NOT NULL,
    [AreaOfBusiness]          VARCHAR (50)     NOT NULL,
    [AreaOfBusinessT]         VARCHAR (50)     NULL,
    [AreaOfBusinessSuffix]    VARCHAR (50)     NOT NULL,
    [AreaOfBusinessSuffixT]   VARCHAR (50)     NULL,
    [PropertyCategoryType]    VARCHAR (50)     NOT NULL,
    [PropertyCategory]        VARCHAR (50)     NOT NULL,
    [SubjectCategory]         VARCHAR (50)     NOT NULL,
    [BillingCompany]          VARCHAR (80)     NOT NULL,
    [IssueSite]               VARCHAR (50)     NULL,
    [AccountantResponsible]   VARCHAR (110)    NULL,
    [ExecResponsible]         VARCHAR (110)    NULL,
    [ProjectionYear]          CHAR (4)         NULL,
    [IncomeProjectionDate]    VARCHAR (10)     NULL,
    [IncomeProjectionDateINT] INT              NULL,
    [SalesCategoryMDS]        NCHAR (50)       NULL,
    [AbbreviationMDS]         NCHAR (30)       NULL,
    [CommissionMDS]           NCHAR (10)       NULL,
    [CommissionNumMDS]        NUMERIC (10, 2)  NULL,
    [CommentMDS]              NVARCHAR (250)   NULL,
    [LegalContact]            VARCHAR (110)    NULL,
    [InvoiceCategory]         VARCHAR (50)     NULL,
    [HeadOfSport]             VARCHAR (110)    DEFAULT ('N/A') NOT NULL,
    [HeadOfBusinessUnit]      VARCHAR (110)    DEFAULT ('N/A') NOT NULL,
    [IsOmitException]         CHAR (3)         DEFAULT ('N/A') NOT NULL,
    [IsReplayReport]          CHAR (3)         DEFAULT ('N/A') NOT NULL,
    [ClientCountry]           VARCHAR (500)    NULL,
    [ClientName]              VARCHAR (500)    NULL,
    [ClientNo]                VARCHAR (500)    NULL,
    [Licensor]                VARCHAR (50)     DEFAULT ('N/A') NOT NULL,
    [ContractingParty]        VARCHAR (50)     DEFAULT ('N/A') NOT NULL,
    [BroadcastDateFrom]       DATETIME         NULL,
    [BroadcastDateTo]         DATETIME         NULL,
    [IsIMGClient]             VARCHAR (31)     NULL,
    [ClientAddress]           VARCHAR (2479)   NULL,
    [ParentPropertyKey]       BIGINT           NULL,
    [HashKey]                 VARBINARY (8000) NOT NULL,
    [DeletedOn]               DATETIME         NULL,
    [ReportingType]           VARCHAR (80)     NULL,
    [PremiereDate]            DATETIME         NULL,
    [AvailabilityDate]        DATETIME         NULL,
	[CreatedDate]			  DATETIME		   NULL,
	[CreatedBy]			      VARCHAR (110)    DEFAULT ('N/A') NOT NULL,
	[UpdatedDate]			  DATETIME		   NULL,
	[UpdatedBy]				  VARCHAR (110)    DEFAULT ('N/A') NOT NULL,
	[Comment]			      VARCHAR (600)	   DEFAULT ('N/A') NOT NULL,
	[CommentCreatedBy]		  VARCHAR (110)    DEFAULT ('N/A') NOT NULL,
	[CommentCreatedDate]	  DATETIME		   NULL,
	[ImgAsAuthorisedSignatory] CHAR (3)        DEFAULT ('N/A') NOT NULL,
	[LicensorInDeal]		  VARCHAR(300)	   DEFAULT ('N/A') NOT NULL,
    [IncludeInOutputDeal]     CHAR (3)         DEFAULT ('N/A') NOT NULL,
    [SellAtRisk]			  CHAR (3)         DEFAULT ('N/A') NOT NULL,
    [LegalOnlineNo]			  INT		       DEFAULT (-1) NOT NULL,
    [ContractStatus]		  VARCHAR (50)	   DEFAULT ('N/A') NOT NULL,
    CONSTRAINT [PK_DimProperty] PRIMARY KEY CLUSTERED ([PropertyKey] ASC)
);






GO


