CREATE TABLE [dbo].[FactAllocations] (
    [AllocationsKey]           BIGINT           NULL,
    [ProjectionYear]           CHAR (4)         NOT NULL,
    [SalesAreaKey]             BIGINT           NOT NULL,
    [IncomeTypeKey]            BIGINT           NOT NULL,
    [PropertyKey]              BIGINT           NOT NULL,
    [ProjectionKey]            BIGINT           NOT NULL,
    [CustomerContactKey]       BIGINT           NOT NULL,
    [ProjectionTerritoryKey]   BIGINT           NOT NULL,
    [CurrencyKey]              BIGINT           NOT NULL,
    [DealKey]                  BIGINT           NOT NULL,
    [InvoicingKey]             BIGINT           NOT NULL,
    [DealPropertyKey]          BIGINT           NOT NULL,
    [DealCreatedByKey]         BIGINT           NOT NULL,
    [DealUpdatedByKey]         BIGINT           NOT NULL,
    [DealCreatedOnDateKey]     INT              NOT NULL,
    [DealUpdatedOnDateKey]     INT              NOT NULL,
    [InvoiceCreatedOnDateKey]  INT              NOT NULL,
    [InvoiceProcessedDateKey]  INT              NOT NULL,
    [DueDateKey]               INT              NOT NULL,
    [ShipDateKey]              INT              DEFAULT ((19000101)) NOT NULL,
    [AllocationCreatedDateKey] INT              DEFAULT ((19000101)) NOT NULL,
    [AllocationUpdatedDateKey] INT              DEFAULT ((19000101)) NOT NULL,
    [DeliveryKey]              BIGINT           NOT NULL,
    [DMDateKey]                INT              DEFAULT ((19000101)) NOT NULL,
    [LicenseStartDateKey]      INT              DEFAULT ((19000101)) NOT NULL,
    [LicenseEndDateKey]        INT              DEFAULT ((19000101)) NOT NULL,
	[EntertainmentShippedDateKey] INT			DEFAULT ((19000101)) NOT NULL,
	[RecognitionDateKey]	   INT				DEFAULT ((19000101)) NOT NULL,
    [PipelineDealKey]          BIGINT           NULL,
	[ContractKey]			   BIGINT			NULL,
	[BillingCode]			   CHAR(9)			NULL,
    [ActualAmount]             MONEY            NOT NULL,
    [ActualAmountUSD]          MONEY            NOT NULL,
    [CountOfAllocation]        BIT              DEFAULT ((0)) NOT NULL,
    [HashKey]                  VARBINARY (8000) NULL,
    [DeletedOn]                DATETIME         NULL,
    CONSTRAINT [FK_FactAllocations_Currency] FOREIGN KEY ([CurrencyKey]) REFERENCES [dbo].[DimCurrency] ([CurrencyKey]),
    CONSTRAINT [FK_FactAllocations_CustomerContact] FOREIGN KEY ([CustomerContactKey]) REFERENCES [dbo].[DimCustomerContact] ([CustomerContactKey]),
    CONSTRAINT [FK_FactAllocations_Deal] FOREIGN KEY ([DealKey]) REFERENCES [dbo].[DimDeal] ([DealKey]),
    CONSTRAINT [FK_FactAllocations_DealCreatedBy] FOREIGN KEY ([DealCreatedByKey]) REFERENCES [dbo].[DimUser] ([UserKey]),
    CONSTRAINT [FK_FactAllocations_DealCreatedOnDate] FOREIGN KEY ([DealCreatedOnDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactAllocations_DealProperty] FOREIGN KEY ([DealPropertyKey]) REFERENCES [dbo].[DimDealProperty] ([DealPropertyKey]),
    CONSTRAINT [FK_FactAllocations_DealUpdatedBy] FOREIGN KEY ([DealUpdatedByKey]) REFERENCES [dbo].[DimUser] ([UserKey]),
    CONSTRAINT [FK_FactAllocations_DealUpdatedOnDate] FOREIGN KEY ([DealUpdatedOnDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactAllocations_DimDelivery] FOREIGN KEY ([DeliveryKey]) REFERENCES [dbo].[DimDelivery] ([DeliveryKey]),
    CONSTRAINT [FK_FactAllocations_DMDateKey] FOREIGN KEY ([DMDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactAllocations_DueDate] FOREIGN KEY ([DueDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactAllocations_IncomeType] FOREIGN KEY ([IncomeTypeKey]) REFERENCES [dbo].[DimIncomeType] ([IncomeTypeKey]),
    CONSTRAINT [FK_FactAllocations_InvoiceCreatedOnDate] FOREIGN KEY ([InvoiceCreatedOnDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactAllocations_InvoiceProcessedDate] FOREIGN KEY ([InvoiceProcessedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactAllocations_Invoicing] FOREIGN KEY ([InvoicingKey]) REFERENCES [dbo].[DimInvoicing] ([InvoicingKey]),
    CONSTRAINT [FK_FactAllocations_PipelineDeal] FOREIGN KEY ([PipelineDealKey]) REFERENCES [dbo].[DimPipelineDeal] ([PipelineDealKey]),
    CONSTRAINT [FK_FactAllocations_ProjectionProperty] FOREIGN KEY ([ProjectionKey]) REFERENCES [dbo].[DimProjection] ([ProjectionKey]),
    CONSTRAINT [FK_FactAllocations_ProjectionTerritory] FOREIGN KEY ([ProjectionTerritoryKey]) REFERENCES [dbo].[DimProjectionTerritory] ([ProjectionTerritoryKey]),
    CONSTRAINT [FK_FactAllocations_ProjectionYear] FOREIGN KEY ([ProjectionYear]) REFERENCES [dbo].[DimProjectionYear] ([ProjectionYear]),
    CONSTRAINT [FK_FactAllocations_Property] FOREIGN KEY ([PropertyKey]) REFERENCES [dbo].[DimProperty] ([PropertyKey]),
    CONSTRAINT [FK_FactAllocations_SalesArea] FOREIGN KEY ([SalesAreaKey]) REFERENCES [dbo].[DimSalesArea] ([SalesAreaKey]),
    CONSTRAINT [FK_FactAllocations_ShipDate] FOREIGN KEY ([ShipDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
	CONSTRAINT [FK_FactAllocations_EntertainmentShippedDate] FOREIGN KEY ([EntertainmentShippedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
	CONSTRAINT [FK_FactAllocations_RecognitionDate] FOREIGN KEY ([RecognitionDateKey]) REFERENCES [dbo].[DimDate] ([DateKey])
);


GO
GRANT VIEW DEFINITION
    ON OBJECT::[dbo].[FactAllocations] TO [DataServices]
    AS [dbo];

